# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 0, 881, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TopMovies = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.TopMovies.setObjectName("TopMovies")
        self.horizontalLayout_4.addWidget(self.TopMovies)
        self.favoritMovies = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.favoritMovies.setObjectName("favoritMovies")
        self.horizontalLayout_4.addWidget(self.favoritMovies)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(620, 540, 89, 25))
        self.searchButton.setObjectName("searchButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 470, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.SearchMovies = QtWidgets.QListWidget(self.centralwidget)
        self.SearchMovies.setGeometry(QtCore.QRect(5, 371, 431, 361))
        self.SearchMovies.setObjectName("SearchMovies")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movies"))
        self.searchButton.setText(_translate("MainWindow", "Search"))


