# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MovieWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MovieWidget(QtWidgets.QWidget):
    def __init__(self, movie ,parent=None):
        super(MovieWidget, self).__init__(parent)
        self.textQVBoxLayout = QtWidgets.QVBoxLayout()
        self.movieTitle = QtWidgets.QLabel()
        self.movieRate = QtWidgets.QLabel()
        self.textQVBoxLayout.addWidget(self.movieTitle)
        self.textQVBoxLayout.addWidget(self.movieRate)
        self.allQHBoxLayout = QtWidgets.QHBoxLayout()
        self.iconQLabel = QtWidgets.QLabel()
        self.allQHBoxLayout.addWidget(self.iconQLabel, 0)
        self.allQHBoxLayout.addLayout(self.textQVBoxLayout, 1)
        self.setLayout(self.allQHBoxLayout)
        # setStyleSheet
        
        self.movieTitle.setText(movie.title)
        self.movieRate.setText(str(movie.rate))

